#!/usr/bin/env bash
# Weekly: render smoke-test PDF report and email to Jeff.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "${SCRIPT_DIR}/../.." && pwd)"
RECIPIENT="${RECIPIENT:-jeffemmett@gmail.com}"

PDF="$(mktemp -t smoke-report-XXXXXX.pdf)"
trap 'rm -f "$PDF"' EXIT

python3 "${REPO}/scripts/smoke-test-report.py" --output "$PDF"

WEEK="$(date +%Y-W%V)"
HOSTNAME_SHORT="$(hostname -s)"
# Don't fail the digest if the log dir is absent — smoke-test-report.py
# already produces an alert PDF for the empty-state case.
LOG_DIR="/var/log/smoke-tests"
[ -d "$LOG_DIR" ] || LOG_DIR="${REPO}/smoke-tests/logs"
SITE_COUNT="$(ls -1 "$LOG_DIR" 2>/dev/null | wc -l || echo 0)"

python3 "${REPO}/scripts/mail_helper.py" \
  --to "$RECIPIENT" \
  --subject "Smoke test report — week ${WEEK}" \
  --body "Automated weekly smoke-test summary from ${HOSTNAME_SHORT}.

Latest run per site is summarized in the attached PDF; failures (if any)
include the tail of the run log.

Source: /opt/dev-ops/smoke-tests/logs/  (${SITE_COUNT} log files scanned)
Generated by: scripts/cron/smoke-report-email.sh" \
  --attach "$PDF"
