#!/usr/bin/env bash
# Propagate a freshly-regenerated Gemini (Google Generative Language) API key.
#
# WHY THIS IS A "PROPAGATION" SCRIPT, NOT A FULL ROTATOR:
#   Google API keys can only be (re)generated by a human in the Cloud Console
#   — there is no mint API. So the one irreducible manual step is yours:
#     https://console.cloud.google.com/apis/credentials  → the Gemini key
#     → "Regenerate key" (keep it restricted to the Generative Language API).
#   This script automates EVERYTHING after that: it pushes the new value to
#   every consumer and marks the inventory rotated.
#
# THE NEW KEY NEVER TOUCHES ARGV:
#   Pass it on stdin or via --key-file. A key passed as a positional arg would
#   land in your shell history, `ps` output, and process logs — re-leaking the
#   very thing you're rotating. The script refuses a key on argv by design.
#
# Usage:
#   # from a file (mode 600):
#   ./rotate-gemini-api-key.sh --key-file /path/to/newkey [--dry-run]
#   # or piped on stdin:
#   pbpaste | ./rotate-gemini-api-key.sh [--dry-run]
#   printf '%s' 'AIza...' | ./rotate-gemini-api-key.sh
#
# Steps:
#   1. Read + validate the new key (AIza-prefixed, ~39 chars).
#   2. Update the local key file the gemini MCP reads (GEMINI_API_KEY_FILE),
#      with a timestamped backup.
#   3. Upsert Infisical rspace:/prod/GEMINI_API_KEY  (write-capable identity
#      lives in Netcup /opt/rspace-online/.env — per the rotate-gemini memory).
#   4. Upsert Infisical claude-ops:/ai/GEMINI_API_KEY (canonical). If the
#      configured identity can't write claude-ops, the script reports it
#      loudly rather than failing silently.
#   5. Restart server-side consumers (gemini-proxy, if present).
#   6. inventory_mark_rotated gemini-api-key.
#
# The gemini MCP server is spawned by Claude Code; it re-reads the key file on
# next launch. Restart Claude Code (or /mcp reconnect) to pick up the new key.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/_lib.sh"

INVENTORY_NAME="gemini-api-key"
LOCAL_KEY_FILE="${LOCAL_KEY_FILE:-/home/jeffe/.private/claude-mcp/gemini-key}"
SSH_TARGET="${SSH_TARGET:-netcup-full}"

# Infisical write context. The rspace universal-auth identity (creds in
# /opt/rspace-online/.env on Netcup) is the proven write path.
INFISICAL_URL="${INFISICAL_URL:-https://secrets.jeffemmett.com}"
RSPACE_ENV="${RSPACE_ENV:-/opt/rspace-online/.env}"

# Server-side consumers to restart after the Infisical value changes.
# Space-separated container names; pruned to those that actually exist.
GEMINI_CONSUMERS="${GEMINI_CONSUMERS:-gemini-proxy}"

KEY_FILE_ARG=""
parse_args() {
  while (( $# > 0 )); do
    case "$1" in
      --dry-run|-n)  DRY_RUN=1; shift ;;
      --key-file|-f) KEY_FILE_ARG="${2:?--key-file needs a path}"; shift 2 ;;
      --help|-h)
        sed -n '2,40p' "$0"; exit 0 ;;
      AIza*|sk-*|*=*)
        die "refusing a key on the command line — pass it via stdin or --key-file (argv leaks into history/logs)" ;;
      *) die "unknown flag: $1" ;;
    esac
  done
}
parse_args "$@"

# Step 1: read + validate the new key (from --key-file or stdin).
if [[ -n "$KEY_FILE_ARG" ]]; then
  [[ -f "$KEY_FILE_ARG" ]] || die "key file not found: $KEY_FILE_ARG"
  NEW_KEY="$(tr -d ' \t\r\n' < "$KEY_FILE_ARG")"
else
  [[ -t 0 ]] && die "no key on stdin and no --key-file given (refusing to prompt interactively for a secret on a TTY in scrollback)"
  NEW_KEY="$(tr -d ' \t\r\n')"
fi
[[ "$NEW_KEY" =~ ^AIza[0-9A-Za-z_-]{30,40}$ ]] \
  || die "new key does not look like a Google API key (expected AIza-prefixed ~39 chars); got ${#NEW_KEY} chars"
log "new key read + format-validated (${#NEW_KEY} chars, value not logged)"

# Step 2: local key file.
if (( DRY_RUN )); then
  log "DRY-RUN: would write new key to $LOCAL_KEY_FILE (mode 600, backup the old)"
else
  if [[ -f "$LOCAL_KEY_FILE" ]]; then
    cp -p "$LOCAL_KEY_FILE" "${LOCAL_KEY_FILE}.bak-pre-rotate-$(date -u +%Y%m%d-%H%M%S)"
  else
    mkdir -p "$(dirname "$LOCAL_KEY_FILE")"
  fi
  umask 077
  printf '%s' "$NEW_KEY" > "$LOCAL_KEY_FILE"
  chmod 600 "$LOCAL_KEY_FILE"
  log "local key file updated: $LOCAL_KEY_FILE"
fi

# Helper: upsert one Infisical secret using a universal-auth identity whose
# CLIENT_ID/CLIENT_SECRET are read from an env file ON THE SERVER. Runs the
# whole flow over SSH so the write-capable creds never leave Netcup. Returns
# non-zero (non-fatal to the script) on failure so one project's permission
# gap doesn't block the others.
infisical_upsert() {
  local project_slug="$1" secret_path="$2" env_path="$3"
  if (( DRY_RUN )); then
    log "DRY-RUN: would upsert ${project_slug}:${secret_path}/GEMINI_API_KEY via identity in ${env_path}"
    return 0
  fi
  NEW_KEY="$NEW_KEY" ssh "$SSH_TARGET" \
    "PROJECT='$project_slug' SECRET_PATH='$secret_path' ENVP='$env_path' INFISICAL_URL='$INFISICAL_URL' NEW_KEY='$NEW_KEY' bash -s" <<'REMOTE'
set -euo pipefail
cid="$(grep -E '^INFISICAL_CLIENT_ID=' "$ENVP" | head -1 | cut -d= -f2- | tr -d '"'"'"'"' )"
csec="$(grep -E '^INFISICAL_CLIENT_SECRET=' "$ENVP" | head -1 | cut -d= -f2- | tr -d '"'"'"'"' )"
[ -n "$cid" ] && [ -n "$csec" ] || { echo "no Infisical creds in $ENVP" >&2; exit 3; }
tok="$(curl -fsS -X POST "$INFISICAL_URL/api/v1/auth/universal-auth/login" \
        -H 'Content-Type: application/json' \
        -d "{\"clientId\":\"$cid\",\"clientSecret\":\"$csec\"}" | python3 -c 'import sys,json;print(json.load(sys.stdin)["accessToken"])')"
[ -n "$tok" ] || { echo "auth failed" >&2; exit 4; }
# Try PATCH (update existing); fall back to POST (create) on 404/not-found.
code=$(curl -fsS -o /tmp/.giresp -w '%{http_code}' -X PATCH \
  "$INFISICAL_URL/api/v3/secrets/raw/GEMINI_API_KEY" \
  -H "Authorization: Bearer $tok" -H 'Content-Type: application/json' \
  -d "{\"projectSlug\":\"$PROJECT\",\"environment\":\"prod\",\"secretPath\":\"$SECRET_PATH\",\"secretValue\":\"$NEW_KEY\"}" 2>/dev/null || true)
if [ "$code" != "200" ]; then
  curl -fsS -X POST "$INFISICAL_URL/api/v3/secrets/raw/GEMINI_API_KEY" \
    -H "Authorization: Bearer $tok" -H 'Content-Type: application/json' \
    -d "{\"projectSlug\":\"$PROJECT\",\"environment\":\"prod\",\"secretPath\":\"$SECRET_PATH\",\"secretValue\":\"$NEW_KEY\"}" >/dev/null
fi
echo "ok"
REMOTE
}

# Step 3: rspace:/prod  (proven write path)
if infisical_upsert "rspace" "/prod" "$RSPACE_ENV"; then
  log "Infisical rspace:/prod/GEMINI_API_KEY upserted ✓"
else
  log "WARNING: failed to upsert rspace:/prod/GEMINI_API_KEY — update it manually (see runbook)"
fi

# Step 4: claude-ops:/ai  (canonical). The rspace identity likely CANNOT write
# claude-ops; this will warn rather than fail. Set CLAUDE_OPS_ENV to a
# write-capable identity's env file to automate it.
CLAUDE_OPS_ENV="${CLAUDE_OPS_ENV:-}"
if [[ -n "$CLAUDE_OPS_ENV" ]]; then
  if infisical_upsert "claude-ops" "/ai" "$CLAUDE_OPS_ENV"; then
    log "Infisical claude-ops:/ai/GEMINI_API_KEY upserted ✓"
  else
    log "WARNING: failed to upsert claude-ops:/ai/GEMINI_API_KEY — update it manually (see runbook)"
  fi
else
  log "NOTE: CLAUDE_OPS_ENV not set — canonical claude-ops:/ai/GEMINI_API_KEY NOT auto-updated."
  log "      Update it manually in the Infisical UI, or set CLAUDE_OPS_ENV to a write-capable identity env file."
fi

# Step 5: restart server-side consumers that exist.
if (( DRY_RUN )); then
  log "DRY-RUN: would restart existing consumers among: $GEMINI_CONSUMERS"
else
  for c in $GEMINI_CONSUMERS; do
    if ssh "$SSH_TARGET" "docker inspect '$c' >/dev/null 2>&1"; then
      ssh "$SSH_TARGET" "docker restart '$c'" >/dev/null && log "restarted consumer: $c"
    else
      log "consumer not present, skipping: $c"
    fi
  done
fi

# Step 6: inventory.
if (( DRY_RUN )); then
  log "DRY-RUN: would inventory_mark_rotated $INVENTORY_NAME"
else
  TODAY=$(inventory_mark_rotated "$INVENTORY_NAME")
  log "inventory_mark_rotated → $TODAY"
fi

cat >&2 <<DONE
[$(date -u +%H:%M:%SZ)] Gemini key propagation complete.
  Local MCP key file: updated → RESTART Claude Code (or /mcp) to reload it.
  Now REVOKE the OLD key in the Cloud Console if you used "create new" instead
  of "regenerate" (regenerate auto-invalidates the old value).
DONE
