services:
  smoke-tests:
    build: .
    image: smoke-tests:latest
    container_name: smoke-tests
    network_mode: host
    volumes:
      - smoke-test-logs:/var/log/smoke-tests
      - /opt/secrets/mailcow:/opt/secrets/mailcow:ro

volumes:
  smoke-test-logs:
