http:
  routers:
    filebrowser:
      rule: "Host(`upload.jefflix.lol`)"
      service: filebrowser
      entryPoints:
        - web
      middlewares:
        - filebrowser-headers

  services:
    filebrowser:
      loadBalancer:
        servers:
          - url: "http://jellyfin-upload:8080"

  middlewares:
    filebrowser-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: https
