http:
  middlewares:
    sablier-postiz-votc:
      plugin:
        sablier:
          sablierUrl: http://sablier:10000
          group: postiz-votc
          sessionDuration: 30m
          dynamic:
            displayName: VOTC Socials
            theme: hacker-terminal
            refreshFrequency: 5s
            showDetails: true
    sablier-postiz-p2pf:
      plugin:
        sablier:
          sablierUrl: http://sablier:10000
          group: postiz-p2pf
          sessionDuration: 30m
          dynamic:
            displayName: P2P Foundation Socials
            theme: hacker-terminal
            refreshFrequency: 5s
            showDetails: true
    sablier-postiz-cc:
      plugin:
        sablier:
          sablierUrl: http://sablier:10000
          group: postiz-cc
          sessionDuration: 30m
          dynamic:
            displayName: CC Socials
            theme: hacker-terminal
            refreshFrequency: 5s
            showDetails: true
  routers:
    postiz-votc:
      rule: "Host(`votc-socials.jeffemmett.com`)"
      entryPoints:
        - web
        - websecure
      middlewares:
        - sablier-postiz-votc
      service: postiz-votc
    postiz-p2pf:
      rule: "Host(`socials.p2pfoundation.net`)"
      entryPoints:
        - web
        - websecure
      middlewares:
        - sablier-postiz-p2pf
      service: postiz-p2pf
    postiz-cc:
      rule: "Host(`socials.crypto-commons.org`) || Host(`socials.valleyofthecommons.com`)"
      entryPoints:
        - web
        - websecure
      middlewares:
        - sablier-postiz-cc
      service: postiz-cc
  services:
    postiz-votc:
      loadBalancer:
        servers:
          - url: "http://postiz-votc:5000"
    postiz-p2pf:
      loadBalancer:
        servers:
          - url: "http://postiz-p2pf:5000"
    postiz-cc:
      loadBalancer:
        servers:
          - url: "http://postiz-cc:5000"
