#!/usr/bin/env python3
"""calibrate-engine-costs.py — derive ForgeCost weights from engine-pool /stats.

Pulls per-engine median/p95 latencies from morpheus-engine-pool's /stats
endpoint and emits a calibration report plus a TypeScript cost block
suitable for pasting into rspace-online-dev's `shared/morpheus/forge-
engine.ts` `builtinEngines` declaration.

Usage:
    # On Netcup (engine-pool reachable on engine-pool-internal):
    ssh netcup-full 'docker exec engine-pool-server curl -s http://localhost:8000/stats' \\
        | python3 scripts/calibrate-engine-costs.py --stdin

    # Or hit a public URL once enginepool.jeffemmett.com is exposed:
    python3 scripts/calibrate-engine-costs.py --url https://enginepool.jeffemmett.com/stats

Cadence: rerun monthly or whenever workload shape changes meaningfully
(new long-form transcription, large-file uploads, etc.).
"""
from __future__ import annotations

import argparse
import json
import sys
import urllib.request

# Heuristic mapping from raw pool engines → external forges that USE them.
# A forge can call multiple pool engines; we attribute its cost to the
# slowest path it commonly takes for a 'convert' verb.
#
# Rough rule: median + 50% headroom (rounded to nearest 10ms) so the
# optimizer doesn't churn on noise. Outliers tracked via p95.
#
# When a forge isn't in the pool (doc-forge, payment-forge, text-forge),
# we keep a hand-tuned default so the optimizer still has SOMETHING to
# rank against the calibrated entries.
HAND_TUNED_DEFAULTS_MS = {
    "doc-forge": 1500,        # libreoffice cold-start + render (no pool)
    "payment-forge": 500,     # on-chain quote round-trip (no pool)
    "text-forge": 5,          # in-process, no IO
}

# Map pool engines to which forge they best represent. image-forge
# delegates to BOTH imagemagick + libvips; the slower (libvips) is the
# safe default for the optimizer's expected-cost estimate.
POOL_TO_FORGE = {
    "ffmpeg": "clip-forge",
    "libvips": "image-forge",   # image-forge prefers libvips for raster
    "imagemagick": None,        # image-forge fallback path; not the primary
    "whisper": None,            # used by clip-forge demux/transcribe path
}


def fetch_stats(url: str) -> dict:
    req = urllib.request.Request(url, headers={"Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=10) as resp:
        return json.loads(resp.read())


def calibrate(stats: dict) -> dict[str, dict]:
    """Map engine-pool stats → forge-keyed cost recommendations."""
    out: dict[str, dict] = {}
    pool_engines = stats.get("engines", {})

    # Engine-pool-derived entries
    for pool_id, forge_id in POOL_TO_FORGE.items():
        if forge_id is None:
            continue
        bucket = pool_engines.get(pool_id) or {}
        n = bucket.get("n") or 0
        median = bucket.get("median_ms")
        p95 = bucket.get("p95_ms")
        if median is None or n < 1:
            continue
        # Round median + 50% headroom to nearest 10 ms.
        ms = max(10, int(round((median * 1.5) / 10.0)) * 10)
        out[forge_id] = {
            "ms": ms,
            "_provenance": {
                "source": "morpheus-engine-pool /stats",
                "pool_engine": pool_id,
                "n_samples": n,
                "median_ms": median,
                "p95_ms": p95,
                "rule": "median * 1.5, rounded to 10 ms",
            },
        }

    # Hand-tuned defaults for forges with no pool path
    for forge_id, ms in HAND_TUNED_DEFAULTS_MS.items():
        if forge_id in out:
            continue
        out[forge_id] = {
            "ms": ms,
            "_provenance": {
                "source": "hand-tuned default",
                "rationale": {
                    "doc-forge": "libreoffice cold-start dominates",
                    "payment-forge": "on-chain quote round-trip",
                    "text-forge": "in-process, no IO",
                }[forge_id],
            },
        }

    return out


def emit_typescript(cal: dict[str, dict]) -> str:
    """Emit a minimal TypeScript snippet showing how to thread cost into
    each builtinEngines handle declaration."""
    lines = ["// Generated by dev-ops/scripts/calibrate-engine-costs.py"]
    lines.append(
        "// Paste each engine's `cost: { ms: <N> }` into its handle "
        "declaration in shared/morpheus/forge-engine.ts."
    )
    lines.append("")
    for forge_id, payload in sorted(cal.items()):
        prov = payload.pop("_provenance", {})
        lines.append(f"// {forge_id}: {json.dumps(prov, sort_keys=True)}")
        lines.append(f"//   cost: {{ ms: {payload['ms']} }}")
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    src = p.add_mutually_exclusive_group(required=True)
    src.add_argument("--url", help="engine-pool /stats URL")
    src.add_argument("--stdin", action="store_true", help="read stats JSON from stdin")
    p.add_argument("--format", choices=("json", "ts"), default="json",
                   help="report format (default: json)")
    args = p.parse_args()

    if args.stdin:
        stats = json.load(sys.stdin)
    else:
        stats = fetch_stats(args.url)

    cal = calibrate(stats)
    if args.format == "ts":
        print(emit_typescript(cal))
    else:
        print(json.dumps(cal, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
