services:
  heart-beat:
    build: .
    container_name: heart-beat
    restart: "no"
    volumes:
      - /opt/apps:/data/apps:ro
      - /opt/websites:/data/websites:ro
      - ./config.yml:/app/config.yml:ro
    env_file: .env
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
    networks:
      - mailcow-network

networks:
  mailcow-network:
    external: true
    name: mailcowdockerized_mailcow-network
